### ISSUE TITLE
GLPK incorrectly reporting that it has found optimal solution to integer program

### ISSUE THREAD

**Issue by zsunberg** [jump-dev/GLPK.jl#147]
Hi all,

I have been solving some integer linear programs with GLPK. GLPK was reporting MOI.OPTIMAL, but I was getting some suspect results (e.g. worse objective after removing a constraint). I tried Gurobi, and, indeed, it found better solutions. I can probably provide an example, but first I want to check if this is somehow expected behavior and whether the problem is with GLPK.jl or GLPK itself. Is it possible that GLPK.jl is translating the status incorrectly? Or could GLPK be finding some suboptimal solution on purpose?

Thanks!

**Comment by mlubin** [comment]
> I want to check if this is somehow expected behavior 

If you're able to find a solution with a better objective value than the value of the `MOI.ObjectiveBound()` attribute, then something is wrong.

> whether the problem is with GLPK.jl or GLPK itself. Is it possible that GLPK.jl is translating the status incorrectly

Anything is possible, hard to say more without a reproducible example.

**Comment by zsunberg** [comment]
Ok, I will see if I can save a problem where this occurs (the full code for creating the problems is quite complex)

**Comment by odow** [comment]
Zach, are you using JuMP? Try `JuMP.write_to_file(model, "model.mof.json")` and email me the resulting file.

**Comment by zsunberg** [comment]
https://gist.github.com/zsunberg/c4923d0da47d11693b3780b106805b6d

```julia
m = JuMP.read_from_file("model.mof.json")
set_optimizer(m, GLPK.Optimizer)
optimize!(m)
@show objective_value(m)
@show MOI.get(m, MOI.ObjectiveBound())
set_optimizer(m, Gurobi.Optimizer)
optimize!(m)
@show objective_value(m)
```
```
objective_value(m) = 4.4502804e7
MOI.get(m, MOI.ObjectiveBound()) = 4.4502804e7
objective_value(m) = 134211.0
```

I guess perhaps it is a numerical issue since Gurobi complains about the large objective coefficients. Still, GLPK should not be so confident in its solution :)

**Comment by odow** [comment]
The issue is that your objective coefficients exceed `Float64` representation
```julia
julia> a, b = extrema(values(objective_function(m).terms))
(1.0, 2.161727821137838e17)

julia> a + b == b
true
```

GLPK should probably warn about numerical issues, but this is a general computing issue, rather than MIP/LP optimization related.

**Comment by zsunberg** [comment]
Ah, OK, thanks for the explanation. Feel free to close, unless JuMP or MOI do any checking for numerical issues that should have caught this.

**Comment by odow** [comment]
Numerical issues in MIP are pretty severe: https://www.gurobi.com/documentation/9.0/refman/num_grb_guidelines_for_num.html

You should be aiming for coefficients between 1e-4 and 1e6. Most solvers use an (absolute) tolerance for optimality on the order of 1e-6.

I think for now we will close. If this question comes up again, we might consider adding some warnings. It's probably more a case for better documentation, rather than a warning in code. I'm planning to give JuMP and MOI's documentation a significant overhaul over the next few months, so I'll add it to my list.
