### ISSUE TITLE
Remove cfunction closure

### ISSUE THREAD

**Issue by BenjaminBastidas** [jump-dev/GLPK.jl#154]
When trying to solve through JUMP a problem using GLPK on a Raspberry Pi using only this package for Julia I get the following error:

`LLVM ERROR: Cannot select: 0x2dbeec8: ch = init_trampoline 0x1379638, 0x25147d8, 0x15aa1a8, 0x2514238, SrcValue:ch<0x2b6e1e8>, SrcValue:ch<0x2a7302c>
  0x25147d8: i32,ch = CopyFromReg 0x1379638, Register:i32 %0
    0x15aee80: i32 = Register %0
  0x15aa1a8: i32 = ARMISD::Wrapper TargetGlobalAddress:i32<i32 (%jl_value_t addrspace(10)**, i32, i32)* @"jlcapi_#15_36057"> 0
    0x19fe480: i32 = TargetGlobalAddress<i32 (%jl_value_t addrspace(10)**, i32, i32)* @"jlcapi_#15_36057"> 0
  0x2514238: i32,ch = CopyFromReg 0x1379638, Register:i32 %1
    0x227b3d0: i32 = Register %1
In function: jlcapi_#15_36057_gfthunkmake
`

Probably because the version of GLPK which is ARM compatible it's not included. So I tried to do a custom install following these steps:

1.  Installed the ARM compatible version of GLPK: sudo apt-get install glpk-utils libglpk-dev glpk-doc python-glpk
2. Tested outside of Julia so I know it's working.
3. I locate the path to the folder containing libglpk.so (/usr/lib/arm-linux-gnueabihf/).
4. I set both temporarily and permanently: ENV["JULIA_GLPK_LIBRARY_PATH"] = "/usr/lib/arm-linux-gnueabihf/"
5. Finally I rebuild: Pkg.build("GLPK")
6. I have also done all these steps both before and after adding the GLPK package with Pkg.add("GLPK").

After everything I've tried I still get the same error message.

Thank you.

**Comment by mlubin** [comment]
I would guess (I may be wrong) that none of the people subscribed to issues in this repository has expertise in debugging LLVM errors on Raspberry Pi. I'd recommend posting on discourse or Julia slack where you might get more eyes.

**Comment by odow** [comment]
Potentially something related to the callback? https://github.com/jump-dev/GLPK.jl/blob/33c6f6e9aaf5162e800c6b0c912ae608f4033330/src/MOI_wrapper/MOI_wrapper.jl#L200-L202

When does the error happen?

I've never seen Julia throw a LLVM error like this. Discourse or Julia slack is the way to go.

**Comment by BenjaminBastidas** [comment]
Thank you both, I posted on discourse already a couple weeks ago, I'm trying with slack right now.

Hello again @odow! As you know I'm actually using your SDDP code. I get the error as soon as I execute the SDDP.PolicyGraph.

**Comment by odow** [comment]
> I get the error as soon as I execute the SDDP.PolicyGraph.

To get help, you'll need to find a reproducible example using GLPK.jl only. Does it happen if you use the `glp_xxx` API functions? Or is it just when creating `GLPK.Optimizer()`?

**Comment by odow** [comment]
@BenjaminBastidas any update on this?

**Comment by BenjaminBastidas** [comment]
@odow Sadly no, I had to stop trying due to time constraints, I'm now using CLP solver on the RPi which is not ideal and quite a bit slower but it's working. I'm sorry I didn't reply to your request but I'm not expert in these subjects so I just didn't fully understand how to do what you asked me. Thank you very much for your help!

**Comment by odow** [comment]
I was interested in whether you got the same error using the low-level functions, like: 
https://github.com/jump-dev/GLPK.jl/blob/master/test/glpk_tst_1.jl

Or whether it only occurred if you did something like
```Julia
import GLPK
const MOI = GLPK.MOI
model = GLPK.Optimizer()
MOI.add_variable(model)
MOI.optimize!(model)
```

**Comment by rofinn** [comment]
I'm not sure if this is related, but we're also seeing issues with the callback code in Julia 1.6 on ARM. In our case, it seems like the closure code isn't supported.

```julia
  cfunction: closures are not supported on this platform
  Stacktrace:
    [1] _set_callback(model::GLPK.Optimizer, callback_function::GLPK.var"#7#8")
      @ GLPK ~/.julia/packages/GLPK/EIflT/src/MOI_wrapper/MOI_wrapper.jl:259
    [2] empty!(model::GLPK.Optimizer)
      @ GLPK ~/.julia/packages/GLPK/EIflT/src/MOI_wrapper/MOI_wrapper.jl:290
    [3] GLPK.Optimizer(; want_infeasibility_certificates::Bool, method::GLPK.MethodEnum, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ GLPK ~/.julia/packages/GLPK/EIflT/src/MOI_wrapper/MOI_wrapper.jl:206
    [4] Optimizer
```

**Comment by odow** [comment]
> it seems like the closure code just isn't supported.

Ah. Correct. I found the documentation that eluded me the first time I searched for this:
https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/#Closure-cfunctions

I guess we could add a flag to disable the default callback. It would mean that some attributes aren't available, but that's better than not running.

**Comment by odow** [comment]
@BenjaminBastidas this should be fixed if you try the new version

**Comment by BenjaminBastidas** [comment]
> @BenjaminBastidas this should be fixed if you try the new version

Indeed, now it works flawlessly. Thank you Oscar!
