### ISSUE TITLE
Can I solve an LP with GLPK using multiple threads?

### ISSUE THREAD

**Issue by bdvalqui** [jump-dev/GLPK.jl#157]
I was trying to use GLPK to solve an LP where I am using parallelization. However, I got the following error:

lp_free: memory allocation error
Error detected in file env/alloc.c at line 72

Thanks in advance for your help.

**Comment by odow** [comment]
Please provide a minimal reproducible example.

There are a number of relevant questions on the Julia discourse that you should read first: https://discourse.julialang.org/search?q=parallel%20category%3A13%20order%3Alatest.

In particular, https://discourse.julialang.org/t/multithreading-unstable-with-jump/49494 has some "gotchas" to be aware of.

**Comment by bdvalqui** [comment]
Hi Oscar,

Thanks for your reply. Sorry for not providing a minimal reproducible example.  

I was able to solve my issue using Gurobi.jl. My code also works with CPLEX.jl. So, it is definitely an issue with GLPK.jl and multithreading when solving an LP which I a still do not understand.
