### ISSUE TITLE
Unfeasibility shooting down Jupyter Notebook kernel

### ISSUE THREAD

**Issue by RicardoTurano** [jump-dev/GLPK.jl#187]
Hi!
I've been using GLPK.jl together with JuMP.jl for my Master's research and found some unexpected behaviour.

By running the following code

    model = Model(GLPK.Optimizer)
    
    @variable(model,0 <= dv <= 8)
    
    @constraints(model, begin 0*dv  >= 1 end)

    @constraints(model, begin 0*dv  == 0 end)
    
    @objective(model, Max, dv)
    
    optimize!(model)

my kernel gets killed. I was expecting that it returns to me some message signaling unfeasibility. That code was running 
at my notebook with julia 1.5.3, ubuntu 18.04.5, GLPK 0.14.4 versions.

I asked @iagoleal to also test this on the Julia REPL and he could reproduce the same error with GLPK, but found that both Xpress and Cbc worked fine.

Thanks!

**Comment by blegat** [comment]
Could you include the error you get from the REPL ?

**Comment by odow** [comment]
```Julia
julia> using JuMP, GLPK

julia> model = Model(GLPK.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK

julia> @variable(model,0 <= dv <= 8)
dv

julia> @constraints(model, begin 0*dv  >= 1 end)

julia> @constraints(model, begin 0*dv  == 0 end)

julia> @objective(model, Max, dv)
dv

julia> optimize!(model)
glp_eval_tab_row: basis factorization does not exist
Error detected in file draft/glpapi12.c at line 808

signal (6): Abort trap: 6
in expression starting at REPL[8]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 55665281 (Pool: 55649517; Big: 15764); GC: 50
zsh: abort      ~/julia --project=/tmp/jump
```

I know what the issue is. I'll make a PR.
