### ISSUE TITLE
Replace internal smaller dicts with functions, named tuples or arrays

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/GLPK.jl#204]
In certain settings, we are repeatedly solving small-ish LPs, in which case the MOI overhead can appear as an important factor.

When collecting the primal results, one repeatedly calls:
```
get(::GLPK.Optimizer, ::MathOptInterface.VariablePrimal, ::MathOptInterface.VariableIndex)
```
which itself calls `MathOptInterface/QxT5e/src/attributes.jl:168, check_result_index_bounds`
which calls `GLPK/mQmKc/src/MOI_wrapper/MOI_wrapper.jl:1960, MethodInstance for get(::GLPK.Optimizer, ::MathOptInterface.ResultCount)` and `_get_status(::GLPK.Optimizer)`

And this one is then superslow because of the getindex on the dictionary: `_RAW_SOLUTION_STATUS[status_code]`

These const Dict, though convenient, become bottlenecks and should be changed to small functions

**Comment by odow** [comment]
Do you have a benchmark on this? I haven't seen `_get_status` show up in any testing.

The ask is to refactor lookups on these into `if-else` statements
https://github.com/jump-dev/GLPK.jl/blob/485c89e10888de9fedf804cbaed7ad4f7fa648f1/src/MOI_wrapper/MOI_wrapper.jl#L1480-L1606

**Comment by matbesancon** [comment]
![image](https://user-images.githubusercontent.com/7623090/151067533-8d84b101-a7f2-4f92-96a1-b0bd456aa90b.png)
the red on top is getindex in dict
```julia
julia> function f(n, optimizer)
       d = randn(n * n)
       x = MOI.get(optimizer, MOI.ListOfVariableIndices())
       obj = dot(d, x)
       MOI.set(optimizer, MOI.ObjectiveFunction{typeof(obj)}(), obj)
       MOI.optimize!(optimizer)
       for _ in 1:10000
           MOI.get.(optimizer, MOI.VariablePrimal(), x)
       end
       end

julia> @profview f(n, optimizer)
```

with n=40

**Comment by matbesancon** [comment]
The model is built with:
```julia
function build_moi_model(n, optimizer = GLPK.Optimizer())
           MOI.set(optimizer, MOI.Silent(), true)
           MOI.set(optimizer, MOI.ObjectiveSense(), MOI.MIN_SENSE)
           (x, _) = MOI.add_constrained_variables(optimizer, fill(MOI.GreaterThan(0.0), n * n))
           xmat = reshape(x, n, n)
           for idx in 1:n
              # column constraint
              MOI.add_constraint(
                  optimizer,
                  sum(1.0 * xmat[:, idx]),
                  MOI.EqualTo(1.0),
              )
              # row constraint
              MOI.add_constraint(
                  optimizer,
                  sum(1.0 * xmat[idx, :]),
                  MOI.EqualTo(1.0),
              )
           end
           return optimizer
       end
```

**Comment by matbesancon** [comment]
Just on the left of the getindex, there is also a repeated call to `glp_get_status(model)` which seems to take quite a bit of time for some reason, it could be cached somewhere?

**Comment by odow** [comment]
Is this from a real use-case? The 10,000 loop seems artificial. 

I'm hesitant to change things because there are a few places in MOI where we've traded readability and maintainability for performance. So yes, we could cache `glp_get_status`, but that adds extra maintenance overhead for the Julia wrapper, and it's already complicated as-is. (We added these caches to Cbc.jl because that had performance problem in normal use-cases, not just artificial benchmarks.)

**Comment by matbesancon** [comment]
The original was from a real use-case, I added the loop to reproduce something similar where getting primal variables can be done many times (because I did not expect this to be such a blocker)

**Comment by matbesancon** [comment]
Even without taking into account the get status part, just replacing the Dict is a huge gain

**Comment by odow** [comment]
#205 addressed the simplex dict. Do we want to address the others?

**Comment by matbesancon** [comment]
maybe indeed. I addressed this one because it was the one I hit in a realistic setting but the others should also be cost-free fixes
