### ISSUE TITLE
support getting node count if possible

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/GLPK.jl#212]
`MOI.get(m, MOI.NodeCount())` fails with `ArgumentError: GLPK.Optimizer does not support getting the attribute MathOptInterface.NodeCount().`

**Comment by odow** [comment]
I'm not aware of a method in GLPK to get this information. That also goes for `SimplexIterations` and `BarrierIterations`.

**Comment by chriscoey** [comment]
Ok, bummer. Thanks and feel free to close

**Comment by odow** [comment]
If anyone reads this in the future and knows how to get this information from GLPK, please comment and I will re-open.
